import { describe, expect, it } from 'bun:test'
import { encodeFrames, FrameAssembler, MAX_FRAME_COUNT, splitUtf8, utf8ByteLength } from '../src/protocol/frames.ts'
describe('bounded workspace frames', () => {
  it('round trips UTF-8 within every wire budget', () => { const json = JSON.stringify({ text: 'é🙂'.repeat(20_000) }); const frames = encodeFrames(json, 8_192); expect(frames.length).toBeGreaterThan(1); expect(frames.every((frame) => utf8ByteLength(frame) <= 8_192)).toBe(true); const assembler = new FrameAssembler(); let value: string | undefined; for (const frame of frames) value = assembler.push(frame); expect(value).toBe(json); expect(assembler.pendingBytes).toBe(0) })
  it('rejects impossible budgets without looping', () => { expect(() => encodeFrames('{}', Number.NaN)).toThrow(/positive integer/); expect(() => encodeFrames('x'.repeat(1_000), 64)).toThrow(/too small/); expect(() => splitUtf8('🙂', 1)).toThrow(/code point/) })
  it('bounds frame count before allocating parts', () => { const assembler = new FrameAssembler(); expect(() => assembler.push(JSON.stringify({ kind: 'frame', id: 'x', index: 0, count: MAX_FRAME_COUNT + 1, data: '' }))).toThrow(/Invalid/); expect(assembler.pendingAssemblyCount).toBe(0) })
  it('bounds aggregate pending assemblies and bytes', () => { const assembler = new FrameAssembler(); assembler.push(JSON.stringify({ kind: 'frame', id: 'a', index: 0, count: 2, data: '1234' }), { maxPendingBytes: 7 }); expect(() => assembler.push(JSON.stringify({ kind: 'frame', id: 'b', index: 0, count: 2, data: '5678' }), { maxPendingBytes: 7 })).toThrow(/assembly limits/); expect(assembler.pendingBytes).toBe(4) })
  it('expires and resets incomplete assemblies', () => { const assembler = new FrameAssembler(); assembler.push(JSON.stringify({ kind: 'frame', id: 'a', index: 0, count: 2, data: 'x' }), { now: 0, timeoutMs: 10 }); expect(assembler.pendingAssemblyCount).toBe(1); expect(assembler.push('plain', { now: 11, timeoutMs: 10 })).toBe('plain'); expect(assembler.pendingAssemblyCount).toBe(0); assembler.push(JSON.stringify({ kind: 'frame', id: 'b', index: 0, count: 2, data: 'y' })); assembler.reset(); expect(assembler.pendingAssemblyCount).toBe(0); expect(assembler.pendingBytes).toBe(0) })
  it('applies the assembly limit to unframed input', () => { expect(() => new FrameAssembler().push('12345', { maxAssembledBytes: 4 })).toThrow(/assembly limits/) })
})
